# Output directories
outdir: 
  hla-loh: results/v6/hla-loh

# Script workspaces
workspaces:
  hla-loh: rules

# Output suffixes
outputs:
  out: outputs
  log: logs
  bench: benchmarks
  work: scratch

# Sheets with anonymized metadata
cluster_paths_sheet: metadata/spectrum_wgs_isabl_filepaths.csv
sample_metadata_sheet: https://docs.google.com/spreadsheets/d/10YbRXTv59kgRu1Fr2bpMVh8kYDK2zg_PCtJB889KgCg/export?format=tsv&id=10YbRXTv59kgRu1Fr2bpMVh8kYDK2zg_PCtJB889KgCg&gid=1903301234

# List of IDs to analyze
patients:
  - SPECTRUM-OV-002
  - SPECTRUM-OV-003
  - SPECTRUM-OV-004
  - SPECTRUM-OV-007
  - SPECTRUM-OV-008
  - SPECTRUM-OV-009
  - SPECTRUM-OV-014
  - SPECTRUM-OV-022
  - SPECTRUM-OV-024
  - SPECTRUM-OV-025
  - SPECTRUM-OV-026
  - SPECTRUM-OV-028
  - SPECTRUM-OV-031
  - SPECTRUM-OV-036
  - SPECTRUM-OV-037
  - SPECTRUM-OV-041
  - SPECTRUM-OV-042
  - SPECTRUM-OV-044
  - SPECTRUM-OV-045
  - SPECTRUM-OV-049
  - SPECTRUM-OV-050
  - SPECTRUM-OV-051
  - SPECTRUM-OV-052
  - SPECTRUM-OV-053
  - SPECTRUM-OV-054
  - SPECTRUM-OV-063
  - SPECTRUM-OV-065
  - SPECTRUM-OV-067
  - SPECTRUM-OV-068
  - SPECTRUM-OV-070
  - SPECTRUM-OV-075
  - SPECTRUM-OV-077
  - SPECTRUM-OV-080
  - SPECTRUM-OV-081
  - SPECTRUM-OV-082
  - SPECTRUM-OV-083
  - SPECTRUM-OV-105
  - SPECTRUM-OV-107
  - SPECTRUM-OV-110
  - SPECTRUM-OV-112
  - SPECTRUM-OV-115
  - SPECTRUM-OV-116
  - SPECTRUM-OV-118

samples:
  tumor:
    - SPECTRUM-OV-002_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-003_S2_PELVIC_PERITONEUM_R1
    - SPECTRUM-OV-004_S1_LEFT_ADNEXA_R1 # last batch
    - SPECTRUM-OV-007_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-008_S1_LEFT_RENAL_LYMPH_NODE_R1
    - SPECTRUM-OV-009_S1_RIGHT_OVARY_R1
    - SPECTRUM-OV-014_S1_BOWEL_R1 # backfilling batch 2
    - SPECTRUM-OV-022_S1_LEFT_OVARY_R1
    - SPECTRUM-OV-025_S1_RECTUM_R1
    - SPECTRUM-OV-026_S1_LIVER_R1
    - SPECTRUM-OV-028_S2_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-031_S1_LEFT_INFRARENAL_LYMPH_NODE_R1
    - SPECTRUM-OV-036_S1_BOWEL_R1
    - SPECTRUM-OV-037_S1_RIGHT_ADNEXA_R1
    - SPECTRUM-OV-041_S1_INFRACOLIC_OMENTUM_R1  # last batch
    - SPECTRUM-OV-041_S1_INFRACOLIC_OMENTUM_R2
    - SPECTRUM-OV-041_S1_ASCITES_R1 # backfilling batch 2
    - SPECTRUM-OV-042_S1_ASCITES_R1 # backfilling batch 2
    - SPECTRUM-OV-044_S1_RIGHT_OVARY_R1
    - SPECTRUM-OV-045_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-049_S1_COLON_R1
    - SPECTRUM-OV-050_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-051_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-052_S2_INFRACOLIC_OMENTUM_R1
    # - SPECTRUM-OV-052_S2_INFRACOLIC_OMENTUM_R2
    - SPECTRUM-OV-053_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-054_S1_INFRACOLIC_OMENTUM_R1
    # - SPECTRUM-OV-014_S2_RIGHT_ABDOMEN_DIAPHRAGM_R1 # Check what is wrong wih variant calling
    - SPECTRUM-OV-024_S1_PELVIC_PERITONEUM_R1
    - SPECTRUM-OV-042_S2_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-052_S2_INFRACOLIC_OMENTUM_R1 # last batch
    - SPECTRUM-OV-052_S1_BOWEL_R1 # backfilling batch 2
    - SPECTRUM-OV-063_S1_LIVER_R1
    - SPECTRUM-OV-065_S1_INFRACOLIC_OMENTUM_R1 # last batch
    - SPECTRUM-OV-065_S1_INFRACOLIC_OMENTUM_R2 # last batch
    - SPECTRUM-OV-067_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-068_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-070_S1_PELVIC_PERITONEUM_INFRACOLIC_OMENTUM_R1 # backfilling batch 1
    # - SPECTRUM-OV-077_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-081_S1_LEFT_OVARY_R1
    - SPECTRUM-OV-082_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-083_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-085_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-090_S1_PELVIC_PERITONEUM_R1 # last batch
    - SPECTRUM-OV-090_S1_PELVIC_PERITONEUM_R2 # last batch
    - SPECTRUM-OV-077_S1_SOFT_TISSUE_THORACIC_DIAPHRAGM_R1
    - SPECTRUM-OV-080_S1_PELVIC_PERITONEUM_ASCITES_R1 # backfilling batch 1
    # - SPECTRUM-OV-105_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-105_S1_INFRACOLIC_OMENTUM_R2
    - SPECTRUM-OV-107_S1_INFRACOLIC_OMENTUM_R1
    - SPECTRUM-OV-107_S1_LEFT_OVARY_R1
    - SPECTRUM-OV-110_S1_LEFT_ABDOMEN_DIAPHRAGM_R1
    - SPECTRUM-OV-112_S1_LEFT_OVARY_R1
    # - SPECTRUM-OV-112_S1_RIGHT_UPPER_QUADRANT_R1
    - SPECTRUM-OV-115_S1_RIGHT_ADNEXA_R1
    - SPECTRUM-OV-075_S3_LARGE_BOWEL_TRANSVERSE_COLON_R1
    - SPECTRUM-OV-116_S1_RIGHT_OVARY_R1
    - SPECTRUM-OV-115_S1_LEFT_OVARY_R1
    - SPECTRUM-OV-118_S1_LEFT_ADNEXA_PELVIC_PERITONEUM_R1 # backfilling batch 1
  normal:
    - SPECTRUM-OV-002_BC1_NORMAL_R1
    - SPECTRUM-OV-004_BC1_NORMAL_R1
    - SPECTRUM-OV-006_BC1_NORMAL_R1
    - SPECTRUM-OV-007_BC1_NORMAL_R1
    - SPECTRUM-OV-008_BC1_NORMAL_R1
    - SPECTRUM-OV-009_BC1_NORMAL_R1
    - SPECTRUM-OV-014_BC1_NORMAL_R1
    - SPECTRUM-OV-022_BC1_NORMAL_R1
    - SPECTRUM-OV-024_BC1_NORMAL_R1
    - SPECTRUM-OV-025_BC1_NORMAL_R1
    - SPECTRUM-OV-026_BC1_NORMAL_R1
    - SPECTRUM-OV-031_BC1_NORMAL_R1
    - SPECTRUM-OV-036_BC1_NORMAL_R1
    - SPECTRUM-OV-037_BC1_NORMAL_R1
    - SPECTRUM-OV-041_BC1_NORMAL_R1
    - SPECTRUM-OV-042_BC1_NORMAL_R1
    - SPECTRUM-OV-044_BC1_NORMAL_R1
    - SPECTRUM-OV-045_BC1_NORMAL_R1
    - SPECTRUM-OV-049_BC1_NORMAL_R1
    - SPECTRUM-OV-050_BC1_NORMAL_R1
    - SPECTRUM-OV-051_BC1_NORMAL_R1
    - SPECTRUM-OV-052_BC1_NORMAL_R1
    - SPECTRUM-OV-053_BC1_NORMAL_R1
    - SPECTRUM-OV-054_BC1_NORMAL_R1
    - SPECTRUM-OV-003_BC1_NORMAL_R1
    - SPECTRUM-OV-028_BC1_NORMAL_R1
    - SPECTRUM-OV-063_BC1_NORMAL_R1
    - SPECTRUM-OV-065_BC1_NORMAL_R1
    - SPECTRUM-OV-067_BC1_NORMAL_R1
    - SPECTRUM-OV-068_BC1_NORMAL_R1
    # - SPECTRUM-OV-070_BC1_NORMAL_R1
    # - SPECTRUM-OV-071_BC1_NORMAL_R1
    - SPECTRUM-OV-075_BC1_NORMAL_R1
    - SPECTRUM-OV-077_BC1_NORMAL_R1
    - SPECTRUM-OV-031_BC1_NORMAL_R2
    - SPECTRUM-OV-041_BC1_NORMAL_R2
    - SPECTRUM-OV-045_BC1_NORMAL_R2
    - SPECTRUM-OV-046_BC1_NORMAL_R1
    - SPECTRUM-OV-080_BC1_NORMAL_R1
    - SPECTRUM-OV-081_BC1_NORMAL_R1
    - SPECTRUM-OV-082_BC1_NORMAL_R1
    - SPECTRUM-OV-083_BC1_NORMAL_R1
    - SPECTRUM-OV-003_BC1_NORMAL_R1
    - SPECTRUM-OV-028_BC1_NORMAL_R1
    - SPECTRUM-OV-092_BC1_NORMAL_R1
    - SPECTRUM-OV-085_BC1_NORMAL_R1
    - SPECTRUM-OV-089_BC1_NORMAL_R1
    - SPECTRUM-OV-090_BC1_NORMAL_R1
    - SPECTRUM-OV-092_BC1_NORMAL_R1
    - SPECTRUM-OV-070_BC1_NORMAL_R1
    - SPECTRUM-OV-071_BC1_NORMAL_R1
    - SPECTRUM-OV-099_BC1_NORMAL_R1
    - SPECTRUM-OV-100_BC1_NORMAL_R1
    - SPECTRUM-OV-105_BC1_NORMAL_R1
    - SPECTRUM-OV-107_BC1_NORMAL_R1
    - SPECTRUM-OV-110_BC1_NORMAL_R1
    - SPECTRUM-OV-112_BC1_NORMAL_R1
    - SPECTRUM-OV-115_BC1_NORMAL_R1
    - SPECTRUM-OV-116_BC1_NORMAL_R1

# Data integration parameters
integrate:
  cohorts:
    SPECTRUM:
      - OV_002
      - OV_003
      - OV_004
      - OV_007
      - OV_008
      - OV_009
      - OV_022
      - OV_025
      - OV_026
      - OV_028
      - OV_031
      - OV_036
      - OV_037
      - OV_041
      - OV_042
      - OV_044
      - OV_045
      - OV_049
      - OV_050
      - OV_051
      - OV_053
      - OV_054
      - OV_063
      - OV_065
      - OV_067
      - OV_068
      - OV_081
      - OV_082
      - OV_083
      - OV_085
      - OV_090
      - OV_100
      - OV_105
      - OV_107
      - OV_110
      - OV_112
      - OV_116
  groups:
    OV_002:
      - SPECTRUM-OV-002_S1_INFRACOLIC_OMENTUM_R1
    OV_003:
      - SPECTRUM-OV-003_S2_PELVIC_PERITONEUM_R1
    OV_007:
      - SPECTRUM-OV-007_S1_INFRACOLIC_OMENTUM_R1
    OV_008:
      - SPECTRUM-OV-008_S1_LEFT_RENAL_LYMPH_NODE_R1
    OV_009:
      - SPECTRUM-OV-009_S1_RIGHT_OVARY_R1
    OV_014:
      - SPECTRUM-OV-014_S2_RIGHT_ABDOMEN_DIAPHRAGM_R1
    OV_022:
      - SPECTRUM-OV-022_S1_LEFT_OVARY_R1
    OV_025:
      - SPECTRUM-OV-025_S1_RECTUM_R1
    OV_026:
      - SPECTRUM-OV-026_S1_LIVER_R1
    OV_028:
      - SPECTRUM-OV-028_S2_INFRACOLIC_OMENTUM_R1
    OV_031:
      - SPECTRUM-OV-031_S1_LEFT_INFRARENAL_LYMPH_NODE_R1
    OV_036:
      - SPECTRUM-OV-036_S1_BOWEL_R1
    OV_037:
      - SPECTRUM-OV-037_S1_RIGHT_ADNEXA_R1
    OV_041:
      - SPECTRUM-OV-041_S1_INFRACOLIC_OMENTUM_R1
      - SPECTRUM-OV-041_S1_INFRACOLIC_OMENTUM_R2
    OV_042:
      - SPECTRUM-OV-042_S2_INFRACOLIC_OMENTUM_R1
    OV_044:
      - SPECTRUM-OV-044_S1_RIGHT_OVARY_R1
    OV_045:
      - SPECTRUM-OV-045_S1_INFRACOLIC_OMENTUM_R1
    OV_049:
      - SPECTRUM-OV-049_S1_COLON_R1
    OV_050:
      - SPECTRUM-OV-050_S1_INFRACOLIC_OMENTUM_R1
    OV_051:
      - SPECTRUM-OV-051_S1_INFRACOLIC_OMENTUM_R1
    OV_052:
      - SPECTRUM-OV-052_S2_INFRACOLIC_OMENTUM_R1
      # - SPECTRUM-OV-052_S2_INFRACOLIC_OMENTUM_R2
    OV_053:
      - SPECTRUM-OV-053_S1_INFRACOLIC_OMENTUM_R1
    OV_054:
      - SPECTRUM-OV-054_S1_INFRACOLIC_OMENTUM_R1
    OV_063:
      - SPECTRUM-OV-063_S1_LIVER_R1
    OV_065:
      - SPECTRUM-OV-065_S1_INFRACOLIC_OMENTUM_R1
      - SPECTRUM-OV-065_S1_INFRACOLIC_OMENTUM_R2
    OV_067:
      - SPECTRUM-OV-067_S1_INFRACOLIC_OMENTUM_R1
    OV_068:
      - SPECTRUM-OV-068_S1_INFRACOLIC_OMENTUM_R1
    OV_082:
      - SPECTRUM-OV-082_S1_INFRACOLIC_OMENTUM_R1
    OV_083:
      - SPECTRUM-OV-083_S1_INFRACOLIC_OMENTUM_R1
    OV_085:
      - SPECTRUM-OV-085_S1_INFRACOLIC_OMENTUM_R1
    OV_090:
      - SPECTRUM-OV-090_S1_PELVIC_PERITONEUM_R1
      - SPECTRUM-OV-090_S1_PELVIC_PERITONEUM_R2
    OV_105:
      # - SPECTRUM-OV-105_S1_INFRACOLIC_OMENTUM_R1
      - SPECTRUM-OV-105_S1_INFRACOLIC_OMENTUM_R2
    OV_107:
      - SPECTRUM-OV-107_S1_INFRACOLIC_OMENTUM_R1
      - SPECTRUM-OV-107_S1_LEFT_OVARY_R1
    OV_110:
      - SPECTRUM-OV-110_S1_LEFT_ABDOMEN_DIAPHRAGM_R1
    OV_112:
      - SPECTRUM-OV-112_S1_LEFT_OVARY_R1
    OV_116:
      - SPECTRUM-OV-116_S1_RIGHT_ABDOMEN_DIAPHRAGM_R1

hla_loh:
  lohhla:
    gatk_dir: /juno/work/shah/vazquezi/software/picard-tools-1.70
    # gatk_dir: /juno/work/shah/vazquezi/software/GenomeAnalysisTK-3.6-0-g89b7209
    # gatk_dir: /juno/work/shah/vazquezi/software/gatk-4.2.5.0
    hla_dat: resources/references/lohhla/hla.dat
    hla_fasta: /juno/work/shah/vazquezi/software/hla-polysolver/data/abc_complete.fasta
    # hla_fasta: resources/references/optitype/hla_reference_dna.fasta
    novo_dir: /juno/work/shah/vazquezi/software/novocraft
    picard_dir: /gsc/software/linux-x86_64-centos6/picard-tools-1.92/
    caller: optitype
    mapping_step: 'TRUE'
    min_coverage_filter: 10
    fishing_step: 'FALSE'
    cleanup: 'FALSE'

genome_build:
  grch37: GRCh37
  grch38: GRCh38